
server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test1?useSSL=false,public
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


